config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  get "up" => "rails/health#show", as: :rails_health_check
  resources :weddings, except: :show do
    resources :guests, only: %i[new create edit update destroy]
    member do
      delete "delete_all_guests", to: "guests#delete_all"
    end
    resources :gifts, only: %i[new create edit update destroy] do
      resources :orders, only: %i[create]
    end
    delete "delete_all_gifts", to: "gifts#delete_all"
    resources :tips, only: %i[new create edit update destroy]
  end
  get "presentes", to: "gifts#index", as: :presentes
  get "presentes/:gift_id/comprar", to: "orders#new", as: :buy_gift
  get "users/:id/dashboard", to: "users#show", as: :user_profile
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :phone, uniqueness: true, length: { minimum: 10, maximum: 15 }
  has_one_attached :photo
  has_one :wedding, dependent: :destroy

  def full_name
    "#{first_name} #{last_name}"
  end

  def initials
    "#{first_name&.chars&.first}#{last_name&.chars&.first}"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    # User info
    @user_wedding = Wedding.includes(:guests, :gifts, orders: :gift).where(user: current_user).first

    # Gift info
    @wedding_gifts = @user_wedding&.gifts || []

    # Guest info
    @wedding_guests = @user_wedding&.guests || []
    @grouped_wedding_guests = @wedding_guests&.group_by(&:confirmed) || []
    if @grouped_wedding_guests[true] && @wedding_guests.count != 0 && @grouped_wedding_guests[true].count != 0
      count_true = @grouped_wedding_guests[true]&.count
      @percentage_minus_not_attending = (count_true * 100) / @wedding_guests.count if @wedding_guests.count != 0 && count_true != 0
    end
    @percentage = @percentage_minus_not_attending || 0

    # Orders info
    @orders = @user_wedding&.orders || []

    # Tips info
    @tips = Tip.where(wedding: @user_wedding)

    # Wedding info
    @couple = @user_wedding ? "#{current_user&.first_name}&#{@user_wedding&.partner_first_name&.capitalize}" : ""
  end
end

app/views/users/_gifts.html.erb
<% if @wedding_gifts.empty? && @user_wedding %>
  <!-- Call-to-action to create the gift list -->
  <section class="h-100 d-flex flex-column align-items-center">
    <div class="d-flex flex-column justify-content-center align-items-center w-75 userw-text-margin">
      <h3 class="userw-text-just userw-title-text mb-5">Parece que temos um <span class="text-white px-1 user-comp-info-progress warning-wedding-message">CASAMENTO!</h3></span>
      <p class="userw-title-text-s userw-text-just-s mb-5">Vamos criar a sua lista?</p>
      <%= link_to "Adicionar lista de presentes", new_wedding_gift_path(@user_wedding), class: "btn btn-outline-dark shadow-sm" %>
    </div>
  </section>
<% elsif @user_wedding.nil? %>
  <!-- No wedding created yet -->
  <section class="h-100 d-flex flex-column align-items-center">
    <div class="d-flex flex-column justify-content-center align-items-center w-75 userw-text-margin">
      <h3 class="userw-text-just userw-title-text mb-5">Ops, parece que o seu casamento ainda não foi criado!</h3>
      <p class="userw-title-text-s userw-text-just-s mb-5"> Por conta disso, não conseguimos gerar a sua lista de presentes. <span class="text-white px-1 user-comp-info-progress">Volte para a aba do casamento</span> e siga as instruções para criá-lo!</p>
      <h3 class="userw-text-just userw-title-text m-0">Nos vemos em breve!</h3>
    </div>
  </section>
<% else %>
  <!-- Wedding gifts list already created -->
  <div class="d-flex justify-content-center">
    <!-- Wedding gifts summary-->
    <h4 class="m-0 pb-4 userw-title-text">Quantidade de presentes cadastrados: <%= @wedding_gifts.count %><h4>
    <span class="d-flex align-items-center ms-5">
      <%= link_to new_wedding_gift_path(@user_wedding) do %>
        <div><i class="fa-solid fa-plus text-success me-2"></i></div>
      <% end %>
      <%= link_to wedding_delete_all_gifts_path(@user_wedding), data: { turbo_method: :delete, turbo_confirm: "Deletar a lista inteira e começar do zero. Você tem certeza?" } do %>
        <div><i class="fa-solid fa-xmark wedding-x-icon"></i></div>
      <% end %>
    </span>
  </div>
  <section class="d-flex flex-wrap" style="gap: .8%">
    <!-- Wedding gifts -->
    <% @wedding_gifts.each do |gift| %>
    <div class="border shadow-sm border-card-wed-user p-2 mb-2 wedding-user-card-size">
      <div class="user-bg-info-wed-content d-flex justify-content-between px-2 py-1 rounded-2">
        <p class="m-0 userw-title-text">Informações:</p>
        <div class="d-flex">
          <%= link_to edit_wedding_gift_path(@user_wedding, gift) do %>
          <div><i class="fa-solid fa-pen user-comp-edit me-2"></i></div>
          <% end %>
          <%= link_to wedding_gift_path(@user_wedding, gift), data: { turbo_method: :delete, turbo_confirm: "Você tem certeza?" } do %>
            <div><i class="fa-solid fa-xmark wedding-x-icon"></i></div>
          <% end %>
        </div>
      </div>
      <span>
        <p class="m-0 mt-2 ps-1 userw-title-text"><%= gift.title %></p>
        <p class="m-0 ps-1 userw-title-text"><%= number_to_currency(gift.value, :unit => "R$ ", :separator => ",", :delimiter => ".") %></p>
        <p class="m-0 ps-1 userw-title-text">Quantidade de cotas: <%= gift.total_quota %></p>
      </span>
    </div>
    <% end %>
  </section>
<% end %>

app/views/users/_guests.html.erb
<% if @wedding_guests.empty? && @user_wedding %>
  <!-- Call-to-action to create the guest list -->
  <section class="h-100 d-flex flex-column align-items-center">
    <div class="d-flex flex-column justify-content-center align-items-center w-75 userw-text-margin">
      <h3 class="userw-text-just userw-title-text mb-5">Parece que temos um <span class="text-white px-1 user-comp-info-progress warning-wedding-message">CASAMENTO!</span></h3>
      <p class="userw-title-text-s userw-text-just-s mb-5">Vamos criar a sua lista?</p>
      <%= link_to "Adicionar lista de convidados", new_wedding_guest_path(@user_wedding), class: "btn btn-outline-dark shadow-sm" %>
    </div>
  </section>
<% elsif @user_wedding.nil? %>
  <!-- No wedding created yet -->
  <section class="h-100 d-flex flex-column align-items-center">
    <div class="d-flex flex-column justify-content-center align-items-center userw-text-margin w-75">
      <h3 class="userw-text-just userw-title-text mb-5">Ops, parece que o seu casamento ainda não foi criado!</h3>
      <p class="userw-title-text-s userw-text-just-s mb-5"> Por conta disso, não conseguimos gerar a sua lista de convidados. <span class="text-white px-1 user-comp-info-progress">Volte para a aba do casamento</span> e siga as instruções para criá-lo!</p>
      <h3 class="userw-text-just userw-title-text mb-4">Nos vemos em breve!</h3>
    </div>
  </section>
<% else %>
  <!-- Wedding guests list already created -->
  <div class="d-flex justify-content-center">
    <!-- Wedding guests summary-->
    <h4 class="m-0 pb-4 userw-title-text">Quantidade de convidados cadastrados: <%= @wedding_guests&.count %><h4>
    <span class="d-flex align-items-center ms-5">
      <%= link_to new_wedding_guest_path(@user_wedding) do %>
        <div><i class="fa-solid fa-plus me-2 text-success"></i></div>
      <% end %>
      <%= link_to delete_all_guests_wedding_path(@user_wedding.id), data: { turbo_method: :delete, turbo_confirm: "Deletar a lista inteira e começar do zero. Você tem certeza?" } do %>
        <div><i class="fa-solid fa-xmark wedding-x-icon"></i></div>
      <% end %>
    </span>
  </div>
    <div class="progress mb-4 border-card-wed-user">
      <!-- Guests confirmation progress bar -->
      <% if @grouped_wedding_guests.include?(true) && @grouped_wedding_guests[true]&.count > 0 %>
        <div class="progress-bar user-comp-info-progress" role="progressbar" aria-label="Example with label" style="width: <%= @percentage %>%;" aria-valuenow="<%= @percentage %>" aria-valuemin="0" aria-valuemax="100"><%= @percentage %>%</div>
      <% else %>
          <div class="progress-bar user-comp-info-progress" role="progressbar" aria-label="Example with label" style="width: 100%;" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100">0%</div>
      <% end %>
    </div>
  <!-- Wedding guests -->
  <section class="d-flex flex-wrap justify-content-between">
    <!-- Confirmed guests -->
    <div class="border shadow-sm border-card-wed-user p-2 mt-1 wedding-user-card-size">
      <div class="d-flex justify-content-center my-1">
        <p class="m-0 pb-2 userw-title-text">Convidados confirmados (<%= @grouped_wedding_guests[true]&.count || 0 %>)</p>
      </div>
      <% @grouped_wedding_guests[true]&.each do |guest| %>
        <span>
          <div class="user-bg-info-wed-content d-flex justify-content-between px-2 py-1 rounded-2">
            <p class="m-0 userw-title-text">Dados:</p>
            <div class="d-flex">
              <%= link_to edit_wedding_guest_path(@user_wedding, guest) do %>
                <div><i class="fa-solid fa-pen user-comp-edit me-2"></i></div>
              <% end %>
              <%= link_to wedding_guest_path(@user_wedding, guest), data: { turbo_method: :delete, turbo_confirm: "Você tem certeza?" } do %>
                <div><i class="fa-solid fa-xmark wedding-x-icon"></i></div>
              <% end %>
            </div>
          </div>
          <div>
            <p class="m-0 mt-2 ps-1 userw-title-text-s">Nome: <%= guest.full_name %></p>
            <p class="m-0 ps-1 userw-title-text-s">Telefone: <%= number_to_phone(guest.phone, pattern: /\A(\d{2})(\d{5})(\d{4})\z/, area_code: true) %> </p>
            <p class="m-0 ps-1 userw-title-text-s">Status: Confirmado</p>
          </div>
          <hr class="border-1">
        </span>
      <% end %>
    </div>

     <!-- Unconfirmed guests -->
    <div class="border shadow-sm border-card-wed-user p-2 mt-1 wedding-user-card-size">
      <div class="d-flex justify-content-center my-1">
        <p class="m-0 pb-2 userw-title-text-s">Convidados a confirmar (<%= @grouped_wedding_guests[nil]&.count || 0 %>)</p>
      </div>
      <% @grouped_wedding_guests[nil]&.each do |guest| %>
        <span>
          <div class="user-bg-info-wed-content d-flex justify-content-between px-2 py-1 rounded-2">
            <p class="m-0 userw-title-text">Dados:</p>
            <div class="d-flex">
              <%= link_to edit_wedding_guest_path(@user_wedding, guest) do %>
              <div><i class="fa-solid fa-pen user-comp-edit me-2"></i></div>
              <% end %>
              <%= link_to wedding_guest_path(@user_wedding, guest), data: { turbo_method: :delete, turbo_confirm: "Você tem certeza?" } do %>
                <div><i class="fa-solid fa-xmark wedding-x-icon"></i></div>
              <% end %>
            </div></div>
          <span>
            <p class="m-0 mt-2 ps-1 userw-title-text-s">Nome: <%= guest.full_name %></p>
            <p class="m-0 ps-1 userw-title-text-s">Telefone: <%= number_to_phone(guest.phone, pattern: /\A(\d{2})(\d{5})(\d{4})\z/, area_code: true) %> </p>
            <p class="m-0 ps-1 userw-title-text-s">Status: A confirmar</p>
          </span>
          <hr class="border-1">
        </span>
      <% end %>
    </div>

     <!-- Not attending guests -->
    <div class="border shadow-sm border-card-wed-user p-2 mt-1 wedding-user-card-size">
      <div>
        <p class="d-flex justify-content-center pb-2 my-1 userw-title-text">Convidados não confirmados (<%= @grouped_wedding_guests[false]&.count || 0 %>)</p>
      </div>
      <% @grouped_wedding_guests[false]&.each do |guest| %>
        <span>
          <div class="user-bg-info-wed-content d-flex justify-content-between px-2 py-1 rounded-2">
            <p class="m-0 userw-title-text">Dados:</p>
            <div class="d-flex">
              <%= link_to edit_wedding_guest_path(@user_wedding, guest) do %>
              <div><i class="fa-solid fa-pen user-comp-edit me-2"></i></div>
              <% end %>
              <%= link_to wedding_guest_path(@user_wedding, guest), data: { turbo_method: :delete, turbo_confirm: "Você tem certeza?" } do %>
                <div><i class="fa-solid fa-xmark wedding-x-icon"></i></div>
              <% end %>
            </div></div>
          <span>
            <p class="m-0 mt-2 ps-1 userw-title-text">Nome: <%= guest.full_name %></p>
            <p class="m-0 ps-1 userw-title-text">Telefone: <%= number_to_phone(guest.phone, pattern: /\A(\d{2})(\d{5})(\d{4})\z/, area_code: true) %> </p>
            <p class="m-0 ps-1 userw-title-text">Status: Não comparecerá</p>
          </span>
          <hr class="border-1">
        </span>
      <% end %>
    </div>
  </section>
<% end %>

app/views/users/_info_wedding.html.erb
<div class="h-100 d-flex flex-column align-items-center">
  <% if @user_wedding %>
    <div class="mt-2">
      <h4 class="userw-title-text">Parabéns, seu casamento foi criado com sucesso! <i class="fa-solid fa-heart" style="color: #ff0026;"></i></h4>
    </div>
    <div class="d-flex flex-column align-items-center w-75">
      <p class="userw-title-text">Compartilhe com seus convidados!</p>
      <%= render 'copy_link' %>
    </div>
    <hr>
    <section class="d-flex w-75 justify-content-between">
      <div class="d-flex flex-column">
        <div class="d-flex">
          <%= link_to root_path do %>
            <div><i class="fa-regular fa-eye me-2 wedding-icons-color"></i></div>
          <% end %>
          <p class="userw-title-text-s">Visualize o seu casamento</p>
        </div>
        <div class="d-flex">
          <%= link_to edit_wedding_path(@user_wedding) do %>
            <div><i class="fa-solid fa-pen user-comp-edit me-2"></i></div>
          <% end %>
          <p class="userw-title-text-s">Alguma informação faltou ou ficou errada? Clique no ícone e edite!</p>
        </div>
        <% if @tips.empty? %>
          <div class="d-flex">
            <%= link_to new_wedding_tip_path(@user_wedding) do %>
              <div><i class="fa-solid fa-plus text-success me-2"></i></div>
            <% end %>
            <p class="userw-title-text-s">Crie sua primeira dica!</p>
          </div>
        <% else %>
          <div class="d-flex">
            <%= link_to new_wedding_tip_path(@user_wedding) do %>
              <div><i class="fa-solid fa-plus text-success me-2"></i></div>
            <% end %>
            <p class="userw-title-text-s">Adicionar mais dicas</p>
          </div>
        <% end %>
        <div class="d-flex">
          <%= link_to wedding_path(@user_wedding), data: { turbo_method: :delete, turbo_confirm: "Você tem certeza?" } do %>
            <div><i class="fa-solid fa-xmark fa-plus me-2 pe-1 wedding-x-icon"></i></div>
          <% end %>
          <p class="userw-title-text-s">Insatisfeito? Remova o seu casamento e crie um novo!</p>
        </div>
      </div>
      <span class="vertical-hr-wed"></span>
      <div class="ms-4">
        <h5 class="p-0 mb-3 userw-title-text">Panorama Geral:</h5>
        <p class="p-0 userw-title-text-s">Convidados: <%= @wedding_guests.count %></p>
        <p class="p-0 userw-title-text-s">Presentes: <%= @wedding_gifts.count %></p>
        <p class="p-0 userw-title-text-s">Presentes Recebidos: <%= @orders.count %></p>
      </div>
    </section>
  <% else %>
    <div class="d-flex flex-column justify-content-center align-items-center w-75 userw-text-margin">
      <h3 class="userw-text-just userw-title-text mb-5">Ops, parece que o seu casamento ainda não foi criado!</h3>
      <p class="userw-title-text-s userw-text-just-s mb-5 mt-1"> Não se preocupe, é muito fácil. Você só precisa <span class="text-white px-1 user-comp-info-progress">clicar no botão abaixo</span> e preencher as informações! Vamos lá?</p>
      <%= link_to "Criar casamento", new_wedding_path, class: "btn btn-outline-warning shadow-sm rounded-3" %>
    </div>
  <% end %>
</div>

app/views/users/_orders.html.erb
<% if @user_wedding.nil? %>
  <section class="h-100 d-flex flex-column align-items-center">
    <div class="d-flex flex-column justify-content-center align-items-center userw-text-margin w-75">
      <h3 class="userw-text-just userw-title-text mb-5">Ops, parece que o seu casamento ainda não foi criado!</h3>
      <p class="userw-title-text-s userw-text-just-s mb-5"> Por conta disso, não há presentes a receber. <span class="text-white px-1" style="background-color: #6f6fab">Volte para a aba do casamento</span> e siga as instruções para criá-lo!</p>
      <h3 class="userw-text-just userw-title-text mb-4">Nos vemos em breve!</h3>
    </div>
  </section>
<% elsif @orders.empty? %>
  <section class="h-100 d-flex flex-column align-items-center">
    <div class="d-flex flex-column justify-content-center align-items-center w-75 userw-text-margin">
      <h3 class="userw-text-just userw-title-text mb-5">Parece que temos um <span class="text-white px-1" style="background-color: #6f6fab; font-variant:all-small-caps; letter-spacing:3px">CASAMENTO!</h3></span>
      <p class="userw-title-text-s userw-text-just-s mb-5">Já já vai aparecer um presente por aqui!</p>
    </div>
  </section>
<% else %>
  <div class="d-flex flex-column align-items-center ">
    <h4 class="m-0 pb-2 userw-title-text">Quantidade de presentes recebidos: <%= @orders&.count %></h4>
    <p class="m-0 pt-2 pb-4 userw-title-text-s">Valor total: <%= number_to_currency(@orders.sum(&:value), :unit => "R$ ", :separator => ",", :delimiter => ".") %></p>
  </div>
  <% @orders.each do |order| %>
    <div class="border shadow-sm border-card-wed-user p-2 my-2 d-flex align-items-center">
      <span class="h-100 flex-grow-1 d-flex justify-content-start align-items-center">
        <div class="d-flex flex-column justify-content-between me-4">
          <p class="m-0 p-0 userw-title-text-s">Presente: <%= order.gift.title %></p>
          <p class="m-0 p-0 userw-title-text-s">Convidado: <%= order.full_name.capitalize %></p>
          <p class="m-0 p-0 userw-title-text-s userw-text-just">Mensagem: <%= order.message.capitalize %></p>
        </div>
      </span>
    </div>
    <span class="horizontal-hr-wed"></span>
  <% end %>
<% end %>

app/views/users/_user_section_choice.html.erb
<div class="flex-grow-1 d-flex flex-column justify-content-between">
  <div class="border h-25 user-comp-info-wed m-3 rounded-4 d-flex justify-content-center align-items-center btn shadow" data-toggle-target="btnDados" data-action="click->toggle#fireChoiceDados">
    <h4 class="fw-bold user-comp-text m-0">Meus dados</h4>
  </div>
  <div class="flex-grow-1 border h-25 user-comp-info-wed m-3 rounded-4 d-flex justify-content-center align-items-center btn shadow" data-toggle-target="btnCasamento" data-action="click->toggle#fireChoiceCasamento">
    <h4 class="fw-bold user-comp-text m-0">Meu casamento</h4>
  </div>
  <div class="flex-grow-1 border h-25 user-comp-info-wed m-3 rounded-4 d-flex justify-content-center align-items-center btn shadow">
    <%= link_to 'Retornar', root_path, class: "h4 text-decoration-none user-comp-text m-0" %>
  </div>
</div>

app/views/users/show.html.erb
<%= render 'shared/navbar' %>
<div class="h-100 vh-75 mt-5">
  <div class="d-flex bg-white justify-content-center h-100" data-controller="toggle">
    <div class="m-3 user-bg-info-wed rounded-4 shadow">
      <%= render "user_section_choice" %>
    </div>
    <div class="flex-grow-1 h-100">
      <%= render "users/user_data/dados_user" %>
      <%= render "users/wedding_data/dados_casamento" %>
    </div>
  </div>
</div>