config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  get "up" => "rails/health#show", as: :rails_health_check
  resources :weddings, except: :show do
    resources :guests, only: %i[new create edit update destroy]
    member do
      delete "delete_all_guests", to: "guests#delete_all"
    end
    resources :gifts, only: %i[new create edit update destroy] do
      resources :orders, only: %i[create]
    end
    delete "delete_all_gifts", to: "gifts#delete_all"
    resources :tips, only: %i[new create edit update destroy]
  end
  get "presentes", to: "gifts#index", as: :presentes
  get "presentes/:gift_id/comprar", to: "orders#new", as: :buy_gift
  get "users/:id/dashboard", to: "users#show", as: :user_profile
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon shadow-sm" id="navbar" style="height: 70px;">
  <div class="container-fluid">
    <%= link_to "/", class: "m-0 ms-2" do %>
      <%= image_tag('20567151.png', class: "vh-4 logo-nav border-none", height: 60) %>
     <% end %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto align-items-center">
        <% if user_signed_in? %>
          <li class="nav-item active me-2">
            <p class="navbar-text m-0" >Olá, <%= current_user.first_name %> </p>
          </li>
          <li class="nav-item dropdown position-static d-flex align-items-center ms-1">
            <a href="#" class="me-2 text-decoration-none" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <span class="d-flex justify-content-center align-items-center fs-5 avatar text-white bg-warning">
                <%= current_user.first_name[0].capitalize %>
              </span>
            </a>
            <div class="dropdown-menu dropdown-menu-end bg-white mx-3" style="border-radius:10px" aria-labelledby="navbarDropdown">
              <%# <section class="buffer-cds" style="background-color:#6F6FAB"></section> %>
              <%= link_to "Dashboard", user_profile_path(current_user), class: "dropdown-item" %>
              <section class="border-bottom-purp"></section>
              <%= link_to "Sair", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
           <%= link_to "Nosso Produto", root_path(anchor: "products"), class: "nav-link text-dark" %>
         </li>
          <li class="nav-item">
              <%= link_to "Nossos Diferenciais", root_path(anchor: "diferenciais"), class: "nav-link text-dark" %>
          </li>
          <li class="nav-item">
            <%= link_to "Cadastre-se", new_user_registration_path, class: "nav-link text-dark" %>
          </li>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link text-dark" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>