config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  get "up" => "rails/health#show", as: :rails_health_check
  resources :weddings, except: :show do
    resources :guests, only: %i[new create edit update destroy]
    member do
      delete "delete_all_guests", to: "guests#delete_all"
    end
    resources :gifts, only: %i[new create edit update destroy] do
      resources :orders, only: %i[create]
    end
    delete "delete_all_gifts", to: "gifts#delete_all"
    resources :tips, only: %i[new create edit update destroy]
  end
  get "presentes", to: "gifts#index", as: :presentes
  get "presentes/:gift_id/comprar", to: "orders#new", as: :buy_gift
  get "users/:id/dashboard", to: "users#show", as: :user_profile
end

app/models/gift.rb
class Gift < ApplicationRecord
  belongs_to :wedding
  has_many :orders, dependent: :destroy
  has_one_attached :photo

  monetize :value_cents

  validates :total_quota, presence: true
  validates :title, presence: true, uniqueness: true
  validates :category, presence: true
  validates :value, presence: true
  validates :photo, presence: true
end

app/controllers/gifts_controller.rb
class GiftsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index]

  def index
    @my = Wedding.last
    @wedding = Wedding.find(@my.id)
    @gifts = Gift.where(wedding: @wedding)
    @order = Order.new
    case params[:sort_by]
    when "value_asc"
      @gifts = @gifts.order(value: :asc)
    when "value_desc"
      @gifts = @gifts.order(value: :desc)
    when "title_asc"
      @gifts = @gifts.order(title: :asc)
    when "title_desc"
      @gifts = @gifts.order(title: :desc)
    when "category"
      @gifts = @gifts.order(category: :asc)
    else
      @gifts
    end
    @couple = "#{@wedding.user.first_name}&#{@wedding.partner_first_name}"
    @wedding_guests_messages = Guest.where(wedding: @wedding).select { |guest| guest.confirmation_message.present? }
    @user_wedding_tips = Tip.where(wedding: @wedding)
  end

  def new
    @gift = Gift.new
    @wedding = Wedding.find(params[:wedding_id])
  end

  def delete_all
    @wedding = Wedding.find(params[:wedding_id])
    @gifts = Gift.where(wedding: @wedding)
    @gifts.each do |gift|
      gift.destroy
    end
    redirect_to user_profile_path(current_user)
  end

  def create
    @gift = Gift.new(gift_params)
    @wedding = Wedding.find(params[:wedding_id])
    @gift.wedding = @wedding
    @gift.save

    redirect_to user_profile_path(current_user)
  end

  def edit
    @gift = Gift.find(params[:id])
    @wedding = Wedding.find(params[:wedding_id])
  end

  def update
    @gift = Gift.find(params[:id])
    @gift.update(gift_params)
    redirect_to user_profile_path(current_user)
  end

  def destroy
    @gift = Gift.find(params[:id])
    @gift.destroy
    redirect_to user_profile_path(current_user)
  end

  private

  def sort_by_title_asc
    Gift.all.sort_by { |gift| [gift.title] }
  end

  def sort_by_value_asc
    Gift.all.sort_by { |gift| [gift.value] }
  end

  def gift_params
    params.require(:gift).permit(:title, :category, :value, :total_quota, :photo)
  end
end

app/views/gifts/_footer.html.erb
<footer class="mt-5">
  <div class="pt-4">
    <div class="container text-center d-flex justify-content-center align-items-center">
      <span>
        <p class="text-muted mb-0 py-2 me-3">Feito com amor por <%= @wedding.partner_first_name.capitalize %> e <%= @wedding.user.first_name.capitalize %> <i class="fa-solid fa-heart" style="color: #ff0026;"></i></p>
      </span>
      <span>
        <a href="#" class="rounded-circle border bg-light p-2"><i class="fa-solid fa-angle-up fa-2xl"></i></a>
      </span>
    </div>
  </div>
</footer>

app/views/gifts/_gift_form.html.erb
<%= simple_form_for [@wedding, @gift] do |f| %>
  <div class="form-inputs scroll-form">
    <%= f.error_notification %>
    <% f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors
    [:base].present? %>

    <%= f.input :title, :label => 'Titulo'%>
    <%= f.input :category, :label => 'Categoria', collection: ['Casa', 'Jantar', 'Outros', 'Passeio', 'Viagem'] %>
    <%= f.input :value, :label => 'Valor' %>
    <%= f.input :total_quota, :label => 'Cotas' %>
    <%= f.input :photo, as: :file, :label => 'Foto do presente' %>
  </div>

  <div class="form-actions pt-4 mb-1 d-flex">
    <%= f.submit "Cadastrar", class: "flex-grow-1 w-100 btn btn-outline-warning shadow-sm me-3"%>
    <%= link_to "Voltar", user_profile_path(current_user), class: "flex-grow-1 w-100 btn btn-outline-warning shadow-sm" %>
  </div>

<% end %>

app/views/gifts/_navbar.html.erb
<ul id="anchors-nav-wed" class="nav justify-content-center align-items-center nav-wed gap-2 anchors-nav-wed-scrollspy">
  <li class="nav-item">
    <%= link_to "Confirme sua presença", '/', class: "nav-link" %>
  </li>
  <li class="nav-item">
    <%= link_to "Recepção", '/', class: "nav-link" %>
  </li>
  <% if !@gifts.empty? %>
    <li class="nav-item">
      <%= link_to "Lista de presentes", presentes_path(), class: "nav-link" %>
    </li>
  <% end %>
  <% if !@wedding_guests_messages.empty? %>
    <li class="nav-item">
      <%= link_to "Mensagens", '/', class: "nav-link" %>
    </li>
  <% end %>
  <% if !@user_wedding_tips.empty? %>
    <li class="nav-item">
      <%= link_to "Dicas", '/', class: "nav-link" %>
    </li>
  <% end %>
</ul>

app/views/gifts/edit.html.erb
<div class="row justify-content-center align-items-center my-4">
  <div class="col-md-6 bg-white p-5 mt-5 rounded-4 shadow">
    <h2 class="text-center mb-4 userw-title-text">Editar presente</h2>
    <%= render "gift_form" %>
  </div>
</div>

app/views/gifts/index.html.erb
<section class="bwed-grey">
  <%= render "navbar"%>
  <section class="bwed-grey-img"></section>
  <div class="container">
    <!-- Gifts filter -->
    <div class="sort-by mt-4" style= "width:17em">
      <form action="<%= presentes_path %>" method="get">
          <select name="sort_by" aria-label="select" style= "width:8.5em">
            <option value="value_asc">Menor Preço</option>
            <option value="value_desc">Maior Preço</option>
            <option value="title_asc">A-Z </option>
            <option value="title_desc">Z-A</option>
            <option value="category">Categoria</option>
          </select>
          <input type="submit" value="Ordernar" class="bnt-gift" >
        </form>
    </div>
    <!-- Gifts -->
    <div class="row">
      <% @gifts.each do |gift|  %>
        <div class="col-3">
          <div class="card-wedding-gift-body">
            <%= cl_image_tag(gift.photo.key, alt: "Image", :gravity=>"center", :crop=>"fill") %>
            <div class="card-wedding-gift-details">
              <div class="card-wedding-gift-info">
                <h5 class="card-wedding-gift-title"> <%= gift.title %> </h5>
                <div class="card-wedding-gift-description">
                  <p> <%= number_to_currency(gift.value, :unit => "R$", :separator => ",", :delimiter => ".") %> </p>
                  <p> <%= gift.category %> </p>
                </div>
              </div>
              <%= link_to "Comprar", buy_gift_path(gift.id), class: "btn bnt-wed-conf" %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
  <%= render "footer"%>
  <section class="buffer-wed"></section>
</section>

app/views/gifts/new.html.erb
<div class="row justify-content-center align-items-center my-4">
  <div class="col-md-6 bg-white p-5 mt-5 rounded-4 shadow">
    <h2 class="text-center mb-4 userw-title-text">Adicionar seus presentes</h2>
    <%= render "gift_form" %>
  </div>
</div>